### ISSUE TITLE
API Response  401

### ISSUE THREAD

**Issue by SkyQuant** [capesean/openiddict-test#8]
I fetched token which is also saved in local storage, but can't authorize for API call. Suppose I have to manually realize auth logic writing something to Startup.cs?

**Comment by capesean** [comment]
I've just run into this issue myself. Will let you know when it's fixed.

**Comment by SkyQuant** [comment]
@capesean, thanks in advance. Any assumptions in the moment?

**Comment by capesean** [comment]
@SkyQuant It's an issue on another repo, see here:
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/232

This being the actual issue:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/360

**Comment by shima20** [comment]
If I wanted to run the openiddict for jwt in production, is there a way to ensure that it doesn't get broken like this?

**Comment by capesean** [comment]
@shima20 you'd need to pin your versions in project.json. i.e. instead of using versions like `1-0-0-*` you'd need to pin them to the exact versions that you have that work, like `1-0-0-rc2-21440`.

**Comment by shima20** [comment]
@capesean good to know thanks!  is there any way to tell which version is a good working version before this bug?

**Comment by capesean** [comment]
@shima20 you'll have to work that out for yourself, I'm afraid. I haven't been keeping track. It's a little tricky because you also have to pin the dependencies, i.e. the other packages that OpenIddict relies on also have to be pinned.

**Comment by kevinchalet** [comment]
FYI, the "missing signature" bug should be fixed soon by @brentschmaltz (who works for the MSFT Azure AD team, in charge of the JWT library OpenIddict relies on): https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/364

**Comment by brentschmaltz** [comment]
@PinpointTownes  Should be in today, sorry for the hassle.
thanks Pinpoint.

**Comment by shima20** [comment]
good to hear @brentschmaltz , looking forward to the fix!

**Comment by kevinchalet** [comment]
@brentschmaltz you're welcome! Thanks for the quick fix :clap:

**Comment by shima20** [comment]
@brentschmaltz is there anything i need to do now?  i tried again this morning and im still getting the same issue.

**Comment by kevinchalet** [comment]
@shima20 https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/232#issuecomment-206936916

**Comment by shima20** [comment]
@PinpointTownes guess we are still waiting for it to be updated?

**Comment by kevinchalet** [comment]
The aspnet-contrib feed is now mirroring the Azure AD feed and ASOS was just updated to use the latest IdentityModel packages: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/e3a8781af075157af944d575d441bab3e7773a05.

The JWT issue you're seeing should disappear when updating your packages.

**Comment by shima20** [comment]
Thank you! It is in fact working again.
